version: '3'
services:
    app:
        image: ghcr.io/archielite/laravel:php8.1
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - postgres  # Change 'mysql' to 'postgres'

    postgres:  # Renamed the service to 'postgres'
        image: postgres:9.6.24  # Specify the PostgreSQL version
        ports:
            - '5432:5432'  # Mapping PostgreSQL port
        environment:
            POSTGRES_PASSWORD: 'mypass'  # Set the PostgreSQL superuser password
            POSTGRES_USER: '${DB_USERNAME}'  # Optionally, specify your username
            POSTGRES_DB: '${DB_DATABASE}'  # Optionally, specify your database name
        volumes:
            - 'sail-postgres:/var/lib/postgresql/data'  # Persist data
        networks:
            - sail
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
            interval: 10s
            retries: 5

networks:
    sail:
        driver: bridge

volumes:
    sail-postgres:  # Renamed volume for clarity
        driver: local
