version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount to /app instead of /var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-crvcak5ds78s73aciiig-a
      - DB_PORT=5432
      - DB_DATABASE=hously
      - DB_USERNAME=root
      - DB_PASSWORD=wZZdeGMTVlIKIV3he4YRwGeWghqN9nLT

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: hously
      POSTGRES_USER: root
      POSTGRES_PASSWORD: wZZdeGMTVlIKIV3he4YRwGeWghqN9nLT
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Reference to custom Nginx config
      - .:/app  # Mount app to /app directory
    depends_on:
      - app  # Ensure Nginx waits for PHP-FPM (app) to start
