version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-crvcak5ds78s73aciiig-a
      - DB_PORT=5432
      - DB_DATABASE=hously
      - DB_USERNAME=root
      - DB_PASSWORD=wZZdeGMTVlIKIV3he4YRwGeWghqN9nLT
    ports:
      - "80:80"  # Map Nginx's port 80 to the host
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: hously
      POSTGRES_USER: root
      POSTGRES_PASSWORD: wZZdeGMTVlIKIV3he4YRwGeWghqN9nLT
    ports:
      - "5432:5432"
